buildConfiguration:
  buildCommand: npm run build
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: ":"

# The site stream allows for specification of site entity whose data will be injected to all
# generation contexts under the `_site` property.
siteStream:
  id: site-entity
  entityId: turtlehead-tacos-site
  fields:
    - name
    - logo
    - c_header
    - c_footer
    - instagramHandle
    - twitterHandle
  localization:
    locales:
      - en